server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: springBoot
  datasource:
    url: jdbc:mysql://localhost:3306/WSWORK?&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect