INSERT INTO tb_factory (ID, NAME, COUNTRY_CODE) VALUES (1, "TOYOTA", 55);
INSERT INTO tb_factory (ID, NAME, COUNTRY_CODE) VALUES (2, "FORD", 55);
INSERT INTO tb_factory (ID, NAME, COUNTRY_CODE) VALUES (3, "BMW", 55);
INSERT INTO tb_factory (ID, NAME, COUNTRY_CODE) VALUES (4, "AUDI", 55);